#!/usr/bin/env python

import os
import socket
import sys

def main(argv):

    whitelist = ['127.0.0.1/8','162.144.11.10','10.0.46.22']
    try:
        if argv[1] in whitelist:
            print 0
            return 0
    except:
        pass

    whitelist.append(socket.gethostbyname(socket.gethostname()))

    if os.path.isfile('/etc/fail2ban/fail2ban_whitelist'):
        with open('/etc/fail2ban/fail2ban_whitelist') as f:
            wl = f.read().splitlines()
            whitelist.extend(wl)

    if os.path.isfile('/etc/ips'):
        with open('/etc/ips') as f:
            etcips = f.read().splitlines()
            for line in etcips:
                etcip = line.split(':', 1)
                whitelist.append(etcip[0])

        try:
            if argv[1] in whitelist:
                print 0
                return 0
            else:
                print 1
                return 1
        except:
            pass


if __name__ == "__main__":
    main(sys.argv)
