#!/usr/bin/env python

import ConfigParser
import sys
import json
import socket

config = ConfigParser.ConfigParser(allow_no_value=True)
config.readfp(open('/etc/net2ban/net2ban.cfg'))


def main(argv):

    n2bsocket = config.get('client', 'socket')
    sock = socket.socket(socket.AF_UNIX)
    sock.settimeout(1)
    sock.connect(n2bsocket)
    data = {'check':'whitelist', 'value':argv[1]}
    msg = json.dumps(data)
    sock.sendall(msg)
    data = sock.recv(1024)
    if data == 'True':
        print "%s is Whitelisted" %argv[1]
        sys.exit(0)
    else:
        print  "%s is NOT Whitelisted" %argv[1]
        sys.exit(1)


if __name__ == "__main__":
    main(sys.argv)
