#!/usr/bin/env python
import argparse
import ConfigParser
import json
import net2ban
import logging

config = ConfigParser.ConfigParser(allow_no_value=True)
config.readfp(open('net2ban.cfg'))
logging.basicConfig(filename='/var/log/net2ban.log', level=logging.INFO)


def main(args):

    msg = {'jail': args.jail,'command': args.command,'value': args.ip,}

    n2b = net2ban.Net2Ban(username=config.get('server', 'username'),
                          password=config.get('server', 'password'),
                          host=config.get('server', 'server'),
                          port=int(config.get('server', 'port')),
                          virtual_host=config.get('server', 'virtual_host'),
                          exchange=config.get('server', 'exchange'),
                          exchange_type=config.get('server', 'exchange_type'),
                          queue=config.get('server', 'queue'),
                          ssl=bool(config.get('server', 'ssl')))

    n2b.connect()
    message = json.dumps(msg)
    n2b.write(message)
    logging.info(message)
    n2b.disconnect()



if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--jail', type=str, default='sshd',
                        help="fail2ban jail to perform command on")
    parser.add_argument('--command', type=str, default='banip',
                        help="fail2ban command to run")
    parser.add_argument('--ip', type=str,
                        help="ip to perform fail2ban command on")
    args = parser.parse_args()
    main(args)
